env:
  start: 1
  step_size: 0.1
  shape:
    x :  30
    y :  30
  horizon: 40
  node_weight: "bimodal" #"constant" # "entropy" constant, linear, bimodal, gp, entropy, steiner_covering, entropy
  disc_size: "small" # large
  n_players : 3
  Cx_lengthscale : 2
  Cx_noise : 0.001
  Fx_lengthscale : 1
  Fx_noise : 0.001
  Cx_beta : 1.5 # only for visu
  Fx_beta : 1.5
  generate: False   # True, False, walls, None: use some fixed save path
  env_file_name: 'env_data.pkl'
  cov_module: 'Matern'     #'Matern', Sq_exp, 'Poly'
  stochasticity: 0.0 
  domains: "single_room"    # two_room
  initial: 0

alg:
  gamma: 1
  # markovian: True
  type: "SRL" #NM, SRL
  ent_coef : 0.0
  epochs: 140
  lr: 0.001

common:
  a: 1
  subgrad: "greedy" #"random" #
  grad: "pytorch" # analytic sym 
  algo: "both" #"both" #"FW_multi" #FW_quasi
  init: "deterministic" #"stochastic" #deterministic
  batch_size: 500
  # corner: 

visu:
  wb: "online" #{'offline', 'online', 'run', 'dryrun', 'disabled'}
  a: 1